
package laboratorio2.FrontEnd;

import laboratorio2.BackEnd.Admin;
import laboratorio2.BackEnd.TheMagic;

public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopUp_AdminLogin = new javax.swing.JDialog();
        Lbl_PopUp_Base = new javax.swing.JLabel();
        IntFrame_PasswordChange = new javax.swing.JInternalFrame();
        Pfield_LastPassword = new javax.swing.JPasswordField();
        Pfield_NewPassword = new javax.swing.JPasswordField();
        Pfield_ConfirmNewPassword = new javax.swing.JPasswordField();
        Btn_ConfirmPasswordChange = new javax.swing.JButton();
        Btn_BackChangePassword = new javax.swing.JButton();
        Lbl_Bg_PasswordChange = new javax.swing.JLabel();
        IntFrame_AdminLogin = new javax.swing.JInternalFrame();
        Pfield_AdminPassword = new javax.swing.JPasswordField();
        Tfield_AdminUser = new javax.swing.JTextField();
        Btn_ConfirmAdminLogin = new javax.swing.JButton();
        Lbl_PasswordChange = new javax.swing.JLabel();
        Button_ExitAdminLogin = new javax.swing.JButton();
        Lbl_Bg_AdminLogin = new javax.swing.JLabel();
        IntFrame_ClientView = new javax.swing.JInternalFrame();
        IntFrame_BuyACar = new javax.swing.JInternalFrame();
        Scroll_Table_CarsList = new javax.swing.JScrollPane();
        Table_CarsList = new javax.swing.JTable();
        Lbl_AdminEntry = new javax.swing.JLabel();
        Lbl_Bg_ClientView = new javax.swing.JLabel();
        IntFrame_AdminView = new javax.swing.JInternalFrame();
        IntFrame_CarsAdminConfig = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        IntFrame_ClientsAdminConfig = new javax.swing.JInternalFrame();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        IntFrame_SalesAdminConfig = new javax.swing.JInternalFrame();
        Btn_CarsAdminConfig = new javax.swing.JButton();
        Btn_ClientsAdminConfig = new javax.swing.JButton();
        Btn_SalesAdminConfig = new javax.swing.JButton();
        Btn_Back_AdminView = new javax.swing.JButton();

        PopUp_AdminLogin.setAlwaysOnTop(true);
        PopUp_AdminLogin.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        PopUp_AdminLogin.setIconImage(null);
        PopUp_AdminLogin.setIconImages(null);
        PopUp_AdminLogin.setLocation(IntFrame_AdminLogin.location());
        PopUp_AdminLogin.setMinimumSize(new java.awt.Dimension(300, 300));
        PopUp_AdminLogin.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        PopUp_AdminLogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_PopUp_Base.setMaximumSize(new java.awt.Dimension(300, 300));
        Lbl_PopUp_Base.setMinimumSize(new java.awt.Dimension(300, 300));
        Lbl_PopUp_Base.setPreferredSize(new java.awt.Dimension(300, 300));
        PopUp_AdminLogin.getContentPane().add(Lbl_PopUp_Base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prototype 1");
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(720, 440));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IntFrame_PasswordChange.setClosable(true);
        IntFrame_PasswordChange.setTitle("Cambio de contraseña");
        IntFrame_PasswordChange.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_PasswordChange.setLayer(2);
        IntFrame_PasswordChange.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_PasswordChange.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_PasswordChange.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_PasswordChange.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_PasswordChange.setVisible(false);
        IntFrame_PasswordChange.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pfield_LastPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pfield_LastPasswordActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Pfield_LastPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 210, -1));

        Pfield_NewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pfield_NewPasswordActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Pfield_NewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 210, -1));

        Pfield_ConfirmNewPassword.setAlignmentX(0.2F);
        Pfield_ConfirmNewPassword.setAlignmentY(0.1F);
        Pfield_ConfirmNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pfield_ConfirmNewPasswordActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Pfield_ConfirmNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 210, -1));

        Btn_ConfirmPasswordChange.setBackground(new java.awt.Color(108, 169, 230));
        Btn_ConfirmPasswordChange.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Btn_ConfirmPasswordChange.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ConfirmPasswordChange.setText("Confirmar");
        Btn_ConfirmPasswordChange.setToolTipText("");
        Btn_ConfirmPasswordChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConfirmPasswordChangeActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Btn_ConfirmPasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 100, -1));

        Btn_BackChangePassword.setBackground(new java.awt.Color(108, 169, 230));
        Btn_BackChangePassword.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Btn_BackChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        Btn_BackChangePassword.setText("Atras");
        Btn_BackChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BackChangePasswordActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Btn_BackChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 100, 30));

        Lbl_Bg_PasswordChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/CambiarContraseña.png"))); // NOI18N
        Lbl_Bg_PasswordChange.setMaximumSize(new java.awt.Dimension(700, 370));
        Lbl_Bg_PasswordChange.setMinimumSize(new java.awt.Dimension(700, 370));
        Lbl_Bg_PasswordChange.setPreferredSize(new java.awt.Dimension(700, 370));
        IntFrame_PasswordChange.getContentPane().add(Lbl_Bg_PasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 380));

        getContentPane().add(IntFrame_PasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_PasswordChange.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_AdminLogin.setClosable(true);
        IntFrame_AdminLogin.setTitle("Inciar Sesión");
        IntFrame_AdminLogin.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_AdminLogin.setLayer(1);
        IntFrame_AdminLogin.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_AdminLogin.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_AdminLogin.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_AdminLogin.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_AdminLogin.setVisible(true);
        IntFrame_AdminLogin.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_AdminLoginInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_AdminLogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pfield_AdminPassword.setBackground(new java.awt.Color(199, 227, 255));
        Pfield_AdminPassword.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Pfield_AdminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pfield_AdminPasswordActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Pfield_AdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 185, 180, 25));

        Tfield_AdminUser.setBackground(new java.awt.Color(199, 227, 255));
        Tfield_AdminUser.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        IntFrame_AdminLogin.getContentPane().add(Tfield_AdminUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 141, 180, 25));

        Btn_ConfirmAdminLogin.setBackground(new java.awt.Color(108, 169, 230));
        Btn_ConfirmAdminLogin.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        Btn_ConfirmAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ConfirmAdminLogin.setText("Ingresar");
        Btn_ConfirmAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConfirmAdminLoginActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Btn_ConfirmAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 110, -1));

        Lbl_PasswordChange.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        Lbl_PasswordChange.setForeground(new java.awt.Color(44, 131, 218));
        Lbl_PasswordChange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_PasswordChange.setText("CAMBIAR CONTRASEÑA");
        Lbl_PasswordChange.setToolTipText("");
        Lbl_PasswordChange.setAlignmentY(0.0F);
        Lbl_PasswordChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_PasswordChangeMouseClicked(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Lbl_PasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 200, 30));

        Button_ExitAdminLogin.setBackground(new java.awt.Color(108, 169, 230));
        Button_ExitAdminLogin.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        Button_ExitAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        Button_ExitAdminLogin.setText("Salir");
        Button_ExitAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExitAdminLoginActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Button_ExitAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 100, 30));

        Lbl_Bg_AdminLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/Fondo-Login.png"))); // NOI18N
        IntFrame_AdminLogin.getContentPane().add(Lbl_Bg_AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        getContentPane().add(IntFrame_AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_AdminLogin.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_ClientView.setTitle("Vista de cliente");
        IntFrame_ClientView.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_ClientView.setMaximumSize(new java.awt.Dimension(960, 540));
        IntFrame_ClientView.setMinimumSize(new java.awt.Dimension(960, 540));
        IntFrame_ClientView.setPreferredSize(new java.awt.Dimension(960, 540));
        try {
            IntFrame_ClientView.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_ClientView.setVisible(true);
        IntFrame_ClientView.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IntFrame_BuyACar.setTitle("menu de compra");
        IntFrame_BuyACar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_BuyACar.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_BuyACar.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_BuyACar.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_BuyACar.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_BuyACar.setVisible(false);

        javax.swing.GroupLayout IntFrame_BuyACarLayout = new javax.swing.GroupLayout(IntFrame_BuyACar.getContentPane());
        IntFrame_BuyACar.getContentPane().setLayout(IntFrame_BuyACarLayout);
        IntFrame_BuyACarLayout.setHorizontalGroup(
            IntFrame_BuyACarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        IntFrame_BuyACarLayout.setVerticalGroup(
            IntFrame_BuyACarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        IntFrame_ClientView.getContentPane().add(IntFrame_BuyACar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_BuyACar.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        Scroll_Table_CarsList.setMaximumSize(new java.awt.Dimension(400, 400));
        Scroll_Table_CarsList.setMinimumSize(new java.awt.Dimension(400, 400));
        Scroll_Table_CarsList.setPreferredSize(new java.awt.Dimension(400, 400));

        Table_CarsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_CarsList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        Table_CarsList.setMaximumSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setMinimumSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setPreferredSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setShowGrid(false);
        Scroll_Table_CarsList.setViewportView(Table_CarsList);

        IntFrame_ClientView.getContentPane().add(Scroll_Table_CarsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 400, 400));

        Lbl_AdminEntry.setText("Entrar a las opciones de administrador");
        Lbl_AdminEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_AdminEntryMouseClicked(evt);
            }
        });
        IntFrame_ClientView.getContentPane().add(Lbl_AdminEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 310, -1));

        Lbl_Bg_ClientView.setMaximumSize(new java.awt.Dimension(960, 510));
        Lbl_Bg_ClientView.setMinimumSize(new java.awt.Dimension(960, 510));
        Lbl_Bg_ClientView.setPreferredSize(new java.awt.Dimension(960, 510));
        IntFrame_ClientView.getContentPane().add(Lbl_Bg_ClientView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 510));

        getContentPane().add(IntFrame_ClientView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));
        try {
            IntFrame_ClientView.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_AdminView.setTitle("Vista de administrador");
        IntFrame_AdminView.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_AdminView.setMaximumSize(new java.awt.Dimension(960, 540));
        IntFrame_AdminView.setMinimumSize(new java.awt.Dimension(960, 540));
        IntFrame_AdminView.setPreferredSize(new java.awt.Dimension(960, 540));
        try {
            IntFrame_AdminView.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_AdminView.setVisible(false);
        IntFrame_AdminView.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IntFrame_CarsAdminConfig.setClosable(true);
        IntFrame_CarsAdminConfig.setTitle("Administrador de autos");
        IntFrame_CarsAdminConfig.setLayer(1);
        IntFrame_CarsAdminConfig.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_CarsAdminConfig.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_CarsAdminConfig.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_CarsAdminConfig.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_CarsAdminConfig.setVisible(false);
        IntFrame_CarsAdminConfig.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_CarsAdminConfigInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        IntFrame_CarsAdminConfig.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 190, 60));

        jButton2.setText("jButton1");
        IntFrame_CarsAdminConfig.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 190, 60));

        jButton3.setText("jButton1");
        IntFrame_CarsAdminConfig.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 190, 60));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        IntFrame_CarsAdminConfig.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 340, 310));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        IntFrame_CarsAdminConfig.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 340, 310));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        IntFrame_CarsAdminConfig.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 340, 310));

        IntFrame_AdminView.getContentPane().add(IntFrame_CarsAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_CarsAdminConfig.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_ClientsAdminConfig.setClosable(true);
        IntFrame_ClientsAdminConfig.setTitle("Administrador de Clientes");
        IntFrame_ClientsAdminConfig.setToolTipText("");
        IntFrame_ClientsAdminConfig.setLayer(1);
        IntFrame_ClientsAdminConfig.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_ClientsAdminConfig.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_ClientsAdminConfig.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_ClientsAdminConfig.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_ClientsAdminConfig.setVisible(false);
        IntFrame_ClientsAdminConfig.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_ClientsAdminConfigInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("jButton1");
        IntFrame_ClientsAdminConfig.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 190, 60));

        jButton5.setText("jButton1");
        IntFrame_ClientsAdminConfig.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 190, 60));

        jButton6.setText("jButton1");
        IntFrame_ClientsAdminConfig.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 190, 60));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        IntFrame_ClientsAdminConfig.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 340, 310));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        IntFrame_ClientsAdminConfig.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 340, 310));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        IntFrame_ClientsAdminConfig.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 340, 310));

        IntFrame_AdminView.getContentPane().add(IntFrame_ClientsAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_ClientsAdminConfig.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_SalesAdminConfig.setClosable(true);
        IntFrame_SalesAdminConfig.setTitle("Administrador de ventas");
        IntFrame_SalesAdminConfig.setLayer(1);
        IntFrame_SalesAdminConfig.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_SalesAdminConfig.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_SalesAdminConfig.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_SalesAdminConfig.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_SalesAdminConfig.setVisible(false);
        IntFrame_SalesAdminConfig.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_SalesAdminConfigInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_SalesAdminConfig.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        IntFrame_AdminView.getContentPane().add(IntFrame_SalesAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_SalesAdminConfig.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        Btn_CarsAdminConfig.setText("Autos");
        Btn_CarsAdminConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CarsAdminConfigActionPerformed(evt);
            }
        });
        IntFrame_AdminView.getContentPane().add(Btn_CarsAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 260, 60));

        Btn_ClientsAdminConfig.setText("Clientes");
        Btn_ClientsAdminConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ClientsAdminConfigActionPerformed(evt);
            }
        });
        IntFrame_AdminView.getContentPane().add(Btn_ClientsAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 260, 60));

        Btn_SalesAdminConfig.setText("Ventas");
        Btn_SalesAdminConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalesAdminConfigActionPerformed(evt);
            }
        });
        IntFrame_AdminView.getContentPane().add(Btn_SalesAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 260, 60));

        Btn_Back_AdminView.setText("Regresar a cliente");
        Btn_Back_AdminView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Back_AdminViewActionPerformed(evt);
            }
        });
        IntFrame_AdminView.getContentPane().add(Btn_Back_AdminView, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 250, 50));

        getContentPane().add(IntFrame_AdminView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));
        try {
            IntFrame_AdminView.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
    * Eventos de formulario
    */
    //Evento de Btn_ConfirmPasswordChange para Autenticar cambio de contraseña
    private void Btn_ConfirmPasswordChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConfirmPasswordChangeActionPerformed
        String Last = String.valueOf(Pfield_LastPassword.getPassword());
        String New = String.valueOf(Pfield_NewPassword.getPassword());
        String Confirm = String.valueOf(Pfield_ConfirmNewPassword.getPassword());
        TheMagic.AutenticatePasswordChange(Last, New, Confirm);
    }//GEN-LAST:event_Btn_ConfirmPasswordChangeActionPerformed
    
    //Evento de Btn_BackChangePassword para regresar a AdminLogin
    private void Btn_BackChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BackChangePasswordActionPerformed
        //Borrar los campos del cambio
        Pfield_LastPassword.setText("");
        Pfield_NewPassword.setText("");
        Pfield_ConfirmNewPassword.setText("");
        //Volver al login de administrador
        IntFrame_PasswordChange.setVisible(false);
        IntFrame_AdminLogin.setVisible(true);
    }//GEN-LAST:event_Btn_BackChangePasswordActionPerformed

    //Evento de Lbl_PasswordChange para llegar al menu de cambio de contraseña
    private void Lbl_PasswordChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_PasswordChangeMouseClicked
        Pfield_AdminPassword.setText("");
        IntFrame_AdminLogin.setVisible(false);
        IntFrame_PasswordChange.setVisible(true);
    }//GEN-LAST:event_Lbl_PasswordChangeMouseClicked

    //Evento de Btn_ConfirmAdminLogin para autenticar inicio de sesion
    private void Btn_ConfirmAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConfirmAdminLoginActionPerformed
        Admin GenCredentials = new Admin();
        GenCredentials.setUser(Tfield_AdminUser.getText());
        GenCredentials.setPassword(String.valueOf(Pfield_AdminPassword.getPassword()));
        TheMagic.Autentication(GenCredentials);
    }//GEN-LAST:event_Btn_ConfirmAdminLoginActionPerformed

    //Evento de Btn_ExitAdminLogin para regresar a ClientView 
    private void Button_ExitAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExitAdminLoginActionPerformed
        IntFrame_AdminLogin.setVisible(false);
        IntFrame_ClientView.setVisible(true);
    }//GEN-LAST:event_Button_ExitAdminLoginActionPerformed

    //Evento al cerrar IntFrame_AdminLogin para volver a ClientView
    private void IntFrame_AdminLoginInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_AdminLoginInternalFrameClosed
        IntFrame_AdminView.setVisible(false);
        IntFrame_ClientView.setVisible(true);
    }//GEN-LAST:event_IntFrame_AdminLoginInternalFrameClosed

    //Evento al cerrar IntFrame_CarsAdminConfig para volver a AdminView
    private void IntFrame_CarsAdminConfigInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_CarsAdminConfigInternalFrameClosed
        IntFrame_ClientView.setVisible(false);
        IntFrame_AdminView.setVisible(true);
    }//GEN-LAST:event_IntFrame_CarsAdminConfigInternalFrameClosed

    //Evento al cerrar IntFrame_ClientsAdminConfig para volver a AdminView
    private void IntFrame_ClientsAdminConfigInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_ClientsAdminConfigInternalFrameClosed
        IntFrame_ClientView.setVisible(false);
        IntFrame_AdminView.setVisible(true);
    }//GEN-LAST:event_IntFrame_ClientsAdminConfigInternalFrameClosed

    //Evento al cerrar IntFrame_SalesAdminConfig para volver a AdminView
    private void IntFrame_SalesAdminConfigInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_SalesAdminConfigInternalFrameClosed
        IntFrame_ClientView.setVisible(false);
        IntFrame_AdminView.setVisible(true);
    }//GEN-LAST:event_IntFrame_SalesAdminConfigInternalFrameClosed

    //Evento de Btn_SalesAdminConfig para entrar a administrador de ventas
    private void Btn_SalesAdminConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalesAdminConfigActionPerformed
        IntFrame_SalesAdminConfig.setVisible(true);
    }//GEN-LAST:event_Btn_SalesAdminConfigActionPerformed

    //Evento de Lbl_AdminEntry para entrar al Admin Login
    private void Lbl_AdminEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_AdminEntryMouseClicked
        IntFrame_AdminLogin.setVisible(true);
    }//GEN-LAST:event_Lbl_AdminEntryMouseClicked

    //Evento de Btn_CarsAdminConfig para entrar al administrador de autos
    private void Btn_CarsAdminConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CarsAdminConfigActionPerformed
        IntFrame_CarsAdminConfig.setVisible(true);
    }//GEN-LAST:event_Btn_CarsAdminConfigActionPerformed

    //Evento de Btn_Back_AdminView para volver a la vista de cliente
    private void Btn_Back_AdminViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Back_AdminViewActionPerformed
        IntFrame_ClientView.setVisible(true);
        IntFrame_AdminView.setVisible(false);
    }//GEN-LAST:event_Btn_Back_AdminViewActionPerformed

    //Evento de Btn_ClientsAdminConfig para entrar al admiistrador de clientes
    private void Btn_ClientsAdminConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ClientsAdminConfigActionPerformed
        IntFrame_ClientsAdminConfig.setVisible(true);
    }//GEN-LAST:event_Btn_ClientsAdminConfigActionPerformed

    private void Pfield_ConfirmNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pfield_ConfirmNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pfield_ConfirmNewPasswordActionPerformed

    private void Pfield_NewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pfield_NewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pfield_NewPasswordActionPerformed

    private void Pfield_LastPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pfield_LastPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pfield_LastPasswordActionPerformed

    private void Pfield_AdminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pfield_AdminPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pfield_AdminPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BackChangePassword;
    private javax.swing.JButton Btn_Back_AdminView;
    private javax.swing.JButton Btn_CarsAdminConfig;
    private javax.swing.JButton Btn_ClientsAdminConfig;
    private javax.swing.JButton Btn_ConfirmAdminLogin;
    private javax.swing.JButton Btn_ConfirmPasswordChange;
    private javax.swing.JButton Btn_SalesAdminConfig;
    private javax.swing.JButton Button_ExitAdminLogin;
    public static javax.swing.JInternalFrame IntFrame_AdminLogin;
    public static javax.swing.JInternalFrame IntFrame_AdminView;
    private javax.swing.JInternalFrame IntFrame_BuyACar;
    public static javax.swing.JInternalFrame IntFrame_CarsAdminConfig;
    public static javax.swing.JInternalFrame IntFrame_ClientView;
    public static javax.swing.JInternalFrame IntFrame_ClientsAdminConfig;
    public static javax.swing.JInternalFrame IntFrame_PasswordChange;
    public static javax.swing.JInternalFrame IntFrame_SalesAdminConfig;
    private javax.swing.JLabel Lbl_AdminEntry;
    private javax.swing.JLabel Lbl_Bg_AdminLogin;
    private javax.swing.JLabel Lbl_Bg_ClientView;
    private javax.swing.JLabel Lbl_Bg_PasswordChange;
    private javax.swing.JLabel Lbl_PasswordChange;
    public static javax.swing.JLabel Lbl_PopUp_Base;
    public static javax.swing.JPasswordField Pfield_AdminPassword;
    public static javax.swing.JPasswordField Pfield_ConfirmNewPassword;
    public static javax.swing.JPasswordField Pfield_LastPassword;
    public static javax.swing.JPasswordField Pfield_NewPassword;
    public static javax.swing.JDialog PopUp_AdminLogin;
    private javax.swing.JScrollPane Scroll_Table_CarsList;
    private javax.swing.JTable Table_CarsList;
    private javax.swing.JTextField Tfield_AdminUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

}