package laboratorio2.FrontEnd;

import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import laboratorio2.BackEnd.Admin;
import laboratorio2.BackEnd.Autos;
import laboratorio2.BackEnd.TheMagic;

public class MainFrame extends javax.swing.JFrame {

    private ArrayList<Autos> automobileRecords = new ArrayList<>();

    public MainFrame() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopUp_AdminLogin = new javax.swing.JDialog();
        Lbl_PopUp_Base = new javax.swing.JLabel();
        IntFrame_PasswordChange = new javax.swing.JInternalFrame();
        Pfield_LastPassword = new javax.swing.JPasswordField();
        Pfield_NewPassword = new javax.swing.JPasswordField();
        Pfield_ConfirmNewPassword = new javax.swing.JPasswordField();
        Btn_ConfirmPasswordChange = new javax.swing.JButton();
        Btn_BackChangePassword = new javax.swing.JButton();
        Lbl_Bg_PasswordChange = new javax.swing.JLabel();
        IntFrame_AdminLogin = new javax.swing.JInternalFrame();
        Pfield_AdminPassword = new javax.swing.JPasswordField();
        Tfield_AdminUser = new javax.swing.JTextField();
        Btn_ConfirmAdminLogin = new javax.swing.JButton();
        Lbl_PasswordChange = new javax.swing.JLabel();
        Button_ExitAdminLogin = new javax.swing.JButton();
        Lbl_Bg_AdminLogin = new javax.swing.JLabel();
        IntFrame_ClientView = new javax.swing.JInternalFrame();
        IntFrame_BuyACar = new javax.swing.JInternalFrame();
        TField_ClientIdentification_Buy = new javax.swing.JTextField();
        TField_ClientName_Buy = new javax.swing.JTextField();
        TField_ClientLastname_Buy = new javax.swing.JTextField();
        TField_ClientBirthday_Buy = new javax.swing.JTextField();
        TField_ClientEmail_Buy = new javax.swing.JTextField();
        TField_ClientPhoneNumber_Buy = new javax.swing.JTextField();
        TField_ClientAdress_Buy = new javax.swing.JTextField();
        Btn_Buy = new javax.swing.JButton();
        Lbl_CarInfo = new javax.swing.JLabel();
        Lbl_Bg_BuyACar = new javax.swing.JLabel();
        Scroll_Table_CarsList = new javax.swing.JScrollPane();
        Table_CarsList = new javax.swing.JTable();
        Lbl_AdminEntry = new javax.swing.JLabel();
        Lbl_Bg_ClientView = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        IntFrame_AdminView = new javax.swing.JInternalFrame();
        IntFrame_CarsAdminConfig = new javax.swing.JInternalFrame();
        jButtonModificar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jTextFieldPrecioModelo = new javax.swing.JTextField();
        jTextFieldPreciodeVenta = new javax.swing.JTextField();
        jTextFieldAño = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldPrecioCompra = new javax.swing.JTextField();
        jTextFieldColor = new javax.swing.JTextField();
        jTextFieldPlaca1 = new javax.swing.JTextField();
        Lbl_Bg_CarsAdminConfig = new javax.swing.JLabel();
        IntFrame_ClientsAdminConfig = new javax.swing.JInternalFrame();
        TField_ClientIdentification = new javax.swing.JTextField();
        TField_ClientName = new javax.swing.JTextField();
        TField_ClientLastname = new javax.swing.JTextField();
        TField_ClientBirthday = new javax.swing.JTextField();
        TField_CLientEmail = new javax.swing.JTextField();
        TField_ClientPhoneNumber = new javax.swing.JTextField();
        TField_ClientAdress = new javax.swing.JTextField();
        Btn_ModifyClient = new javax.swing.JButton();
        Btn_DeleteClient = new javax.swing.JButton();
        Lbl_Bg_ClientsAdminConfig = new javax.swing.JLabel();
        IntFrame_SalesAdminConfig = new javax.swing.JInternalFrame();
        Btn_Back_AdminView = new javax.swing.JButton();
        Lbl_Entry_CarsAdminConfig = new javax.swing.JLabel();
        Lbl_Entry_ClientsAdminConfig = new javax.swing.JLabel();
        Lbl_Entry_SalesAdminConfig = new javax.swing.JLabel();
        Lbl_Bg_AdminView = new javax.swing.JLabel();
        jMenuBarAcercade = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAcercade = new javax.swing.JMenuItem();
        jMenuItemInstrucciones = new javax.swing.JMenuItem();

        PopUp_AdminLogin.setAlwaysOnTop(true);
        PopUp_AdminLogin.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        PopUp_AdminLogin.setIconImage(null);
        PopUp_AdminLogin.setIconImages(null);
        PopUp_AdminLogin.setLocation(IntFrame_AdminLogin.location());
        PopUp_AdminLogin.setMinimumSize(new java.awt.Dimension(300, 300));
        PopUp_AdminLogin.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        PopUp_AdminLogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_PopUp_Base.setMaximumSize(new java.awt.Dimension(300, 300));
        Lbl_PopUp_Base.setMinimumSize(new java.awt.Dimension(300, 300));
        Lbl_PopUp_Base.setPreferredSize(new java.awt.Dimension(300, 300));
        PopUp_AdminLogin.getContentPane().add(Lbl_PopUp_Base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prototype 1");
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(720, 440));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IntFrame_PasswordChange.setClosable(true);
        IntFrame_PasswordChange.setTitle("Cambio de contraseña");
        IntFrame_PasswordChange.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_PasswordChange.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_PasswordChange.setLayer(2);
        IntFrame_PasswordChange.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_PasswordChange.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_PasswordChange.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_PasswordChange.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_PasswordChange.setVisible(false);
        IntFrame_PasswordChange.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pfield_LastPassword.setBackground(new java.awt.Color(199, 227, 255));
        Pfield_LastPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pfield_LastPasswordActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Pfield_LastPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 210, -1));

        Pfield_NewPassword.setBackground(new java.awt.Color(199, 227, 255));
        Pfield_NewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pfield_NewPasswordActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Pfield_NewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 210, -1));

        Pfield_ConfirmNewPassword.setBackground(new java.awt.Color(199, 227, 255));
        Pfield_ConfirmNewPassword.setAlignmentX(0.2F);
        Pfield_ConfirmNewPassword.setAlignmentY(0.1F);
        Pfield_ConfirmNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pfield_ConfirmNewPasswordActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Pfield_ConfirmNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 210, -1));

        Btn_ConfirmPasswordChange.setBackground(new java.awt.Color(108, 169, 230));
        Btn_ConfirmPasswordChange.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Btn_ConfirmPasswordChange.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ConfirmPasswordChange.setText("Confirmar");
        Btn_ConfirmPasswordChange.setToolTipText("");
        Btn_ConfirmPasswordChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConfirmPasswordChangeActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Btn_ConfirmPasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 100, -1));

        Btn_BackChangePassword.setBackground(new java.awt.Color(108, 169, 230));
        Btn_BackChangePassword.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Btn_BackChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        Btn_BackChangePassword.setText("Atras");
        Btn_BackChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BackChangePasswordActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Btn_BackChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 100, 30));

        Lbl_Bg_PasswordChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/CambiarContraseña.png"))); // NOI18N
        IntFrame_PasswordChange.getContentPane().add(Lbl_Bg_PasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 380));

        getContentPane().add(IntFrame_PasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_PasswordChange.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_AdminLogin.setClosable(true);
        IntFrame_AdminLogin.setTitle("Iniciar Sesión");
        IntFrame_AdminLogin.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_AdminLogin.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_AdminLogin.setLayer(1);
        IntFrame_AdminLogin.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_AdminLogin.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_AdminLogin.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_AdminLogin.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_AdminLogin.setVisible(true);
        IntFrame_AdminLogin.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_AdminLoginInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_AdminLogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pfield_AdminPassword.setBackground(new java.awt.Color(199, 227, 255));
        Pfield_AdminPassword.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Pfield_AdminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pfield_AdminPasswordActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Pfield_AdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 185, 180, 25));

        Tfield_AdminUser.setBackground(new java.awt.Color(199, 227, 255));
        Tfield_AdminUser.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Tfield_AdminUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tfield_AdminUserActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Tfield_AdminUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 141, 180, 25));

        Btn_ConfirmAdminLogin.setBackground(new java.awt.Color(108, 169, 230));
        Btn_ConfirmAdminLogin.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        Btn_ConfirmAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ConfirmAdminLogin.setText("Ingresar");
        Btn_ConfirmAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConfirmAdminLoginActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Btn_ConfirmAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, 30));

        Lbl_PasswordChange.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        Lbl_PasswordChange.setForeground(new java.awt.Color(44, 131, 218));
        Lbl_PasswordChange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_PasswordChange.setText("CAMBIAR CONTRASEÑA");
        Lbl_PasswordChange.setToolTipText("");
        Lbl_PasswordChange.setAlignmentY(0.0F);
        Lbl_PasswordChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_PasswordChangeMouseClicked(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Lbl_PasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 200, 30));

        Button_ExitAdminLogin.setBackground(new java.awt.Color(108, 169, 230));
        Button_ExitAdminLogin.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        Button_ExitAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        Button_ExitAdminLogin.setText("Salir");
        Button_ExitAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExitAdminLoginActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Button_ExitAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 100, 30));

        Lbl_Bg_AdminLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/Fondo-Login.png"))); // NOI18N
        IntFrame_AdminLogin.getContentPane().add(Lbl_Bg_AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        getContentPane().add(IntFrame_AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_AdminLogin.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_ClientView.setTitle("Vista de cliente");
        IntFrame_ClientView.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_ClientView.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_ClientView.setMaximumSize(new java.awt.Dimension(960, 540));
        IntFrame_ClientView.setMinimumSize(new java.awt.Dimension(960, 540));
        IntFrame_ClientView.setPreferredSize(new java.awt.Dimension(960, 540));
        try {
            IntFrame_ClientView.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_ClientView.setVisible(true);
        IntFrame_ClientView.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IntFrame_BuyACar.setClosable(true);
        IntFrame_BuyACar.setTitle("Menú de compra");
        IntFrame_BuyACar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_BuyACar.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_BuyACar.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_BuyACar.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_BuyACar.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_BuyACar.setVisible(false);
        IntFrame_BuyACar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TField_ClientIdentification_Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientIdentification_BuyActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(TField_ClientIdentification_Buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 180, 20));

        TField_ClientName_Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientName_BuyActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(TField_ClientName_Buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 180, 20));

        TField_ClientLastname_Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientLastname_BuyActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(TField_ClientLastname_Buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, 20));

        TField_ClientBirthday_Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientBirthday_BuyActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(TField_ClientBirthday_Buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 213, 180, 20));

        TField_ClientEmail_Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientEmail_BuyActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(TField_ClientEmail_Buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 255, 180, 20));

        TField_ClientPhoneNumber_Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientPhoneNumber_BuyActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(TField_ClientPhoneNumber_Buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 295, 180, 20));

        TField_ClientAdress_Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientAdress_BuyActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(TField_ClientAdress_Buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 333, 180, 20));

        Btn_Buy.setBackground(new java.awt.Color(108, 169, 230));
        Btn_Buy.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        Btn_Buy.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Buy.setText("Comprar");
        Btn_Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuyActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(Btn_Buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 170, 50));

        Lbl_CarInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_CarInfo.setText("*Aqui se muetran los datos del auto que se va a comprar*");
        IntFrame_BuyACar.getContentPane().add(Lbl_CarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 300, 170));

        Lbl_Bg_BuyACar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/RegistrarClientes.png"))); // NOI18N
        IntFrame_BuyACar.getContentPane().add(Lbl_Bg_BuyACar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        IntFrame_ClientView.getContentPane().add(IntFrame_BuyACar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_BuyACar.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        Scroll_Table_CarsList.setMaximumSize(new java.awt.Dimension(560, 400));
        Scroll_Table_CarsList.setMinimumSize(new java.awt.Dimension(560, 400));
        Scroll_Table_CarsList.setPreferredSize(new java.awt.Dimension(560, 400));

        Table_CarsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_CarsList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        Table_CarsList.setMaximumSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setMinimumSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setPreferredSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setShowGrid(false);
        Scroll_Table_CarsList.setViewportView(Table_CarsList);

        IntFrame_ClientView.getContentPane().add(Scroll_Table_CarsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 560, 400));

        Lbl_AdminEntry.setText("Entrar a las opciones de administrador");
        Lbl_AdminEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_AdminEntryMouseClicked(evt);
            }
        });
        IntFrame_ClientView.getContentPane().add(Lbl_AdminEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 310, -1));

        Lbl_Bg_ClientView.setMaximumSize(new java.awt.Dimension(960, 510));
        Lbl_Bg_ClientView.setMinimumSize(new java.awt.Dimension(960, 510));
        Lbl_Bg_ClientView.setPreferredSize(new java.awt.Dimension(960, 510));
        IntFrame_ClientView.getContentPane().add(Lbl_Bg_ClientView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 510));
        IntFrame_ClientView.setJMenuBar(jMenuBar2);

        getContentPane().add(IntFrame_ClientView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));
        try {
            IntFrame_ClientView.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_AdminView.setTitle("Vista de administrador");
        IntFrame_AdminView.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_AdminView.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_AdminView.setMaximumSize(new java.awt.Dimension(960, 540));
        IntFrame_AdminView.setMinimumSize(new java.awt.Dimension(960, 540));
        IntFrame_AdminView.setPreferredSize(new java.awt.Dimension(960, 540));
        try {
            IntFrame_AdminView.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_AdminView.setVisible(false);
        IntFrame_AdminView.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IntFrame_CarsAdminConfig.setClosable(true);
        IntFrame_CarsAdminConfig.setTitle("Administrador de autos");
        IntFrame_CarsAdminConfig.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_CarsAdminConfig.setLayer(1);
        IntFrame_CarsAdminConfig.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_CarsAdminConfig.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_CarsAdminConfig.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_CarsAdminConfig.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_CarsAdminConfig.setVisible(false);
        IntFrame_CarsAdminConfig.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_CarsAdminConfigInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonModificar.setBackground(new java.awt.Color(108, 169, 230));
        jButtonModificar.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 180, 60));

        jButtonRegistrar.setBackground(new java.awt.Color(108, 169, 230));
        jButtonRegistrar.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 180, 60));

        jButtonEliminar.setBackground(new java.awt.Color(108, 169, 230));
        jButtonEliminar.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 180, 60));

        jTextFieldPrecioModelo.setEditable(false);
        jTextFieldPrecioModelo.setBackground(new java.awt.Color(199, 227, 255));
        jTextFieldPrecioModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioModeloActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldPrecioModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 210, -1));

        jTextFieldPreciodeVenta.setEditable(false);
        jTextFieldPreciodeVenta.setBackground(new java.awt.Color(199, 227, 255));
        jTextFieldPreciodeVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPreciodeVentaActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldPreciodeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 210, -1));

        jTextFieldAño.setBackground(new java.awt.Color(199, 227, 255));
        jTextFieldAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAñoActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 247, 210, 20));

        jTextFieldMarca.setBackground(new java.awt.Color(199, 227, 255));
        jTextFieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMarcaActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 210, -1));

        jTextFieldPrecioCompra.setBackground(new java.awt.Color(199, 227, 255));
        jTextFieldPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioCompraActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 210, -1));

        jTextFieldColor.setBackground(new java.awt.Color(199, 227, 255));
        jTextFieldColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColorActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 210, 20));

        jTextFieldPlaca1.setBackground(new java.awt.Color(199, 227, 255));
        jTextFieldPlaca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaca1ActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldPlaca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 63, 210, 20));

        Lbl_Bg_CarsAdminConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/RegistroAutoFin.png"))); // NOI18N
        IntFrame_CarsAdminConfig.getContentPane().add(Lbl_Bg_CarsAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 360));

        IntFrame_AdminView.getContentPane().add(IntFrame_CarsAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_CarsAdminConfig.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_ClientsAdminConfig.setClosable(true);
        IntFrame_ClientsAdminConfig.setTitle("Administrador de Clientes");
        IntFrame_ClientsAdminConfig.setToolTipText("");
        IntFrame_ClientsAdminConfig.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_ClientsAdminConfig.setLayer(1);
        IntFrame_ClientsAdminConfig.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_ClientsAdminConfig.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_ClientsAdminConfig.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_ClientsAdminConfig.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_ClientsAdminConfig.setVisible(false);
        IntFrame_ClientsAdminConfig.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_ClientsAdminConfigInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TField_ClientIdentification.setBackground(new java.awt.Color(199, 227, 255));
        TField_ClientIdentification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientIdentificationActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(TField_ClientIdentification, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 180, 20));

        TField_ClientName.setBackground(new java.awt.Color(199, 227, 255));
        TField_ClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientNameActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(TField_ClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 180, 20));

        TField_ClientLastname.setBackground(new java.awt.Color(199, 227, 255));
        TField_ClientLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientLastnameActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(TField_ClientLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 172, 180, 20));

        TField_ClientBirthday.setBackground(new java.awt.Color(199, 227, 255));
        TField_ClientBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientBirthdayActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(TField_ClientBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 213, 180, 20));

        TField_CLientEmail.setBackground(new java.awt.Color(199, 227, 255));
        TField_CLientEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_CLientEmailActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(TField_CLientEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 255, 180, 20));

        TField_ClientPhoneNumber.setBackground(new java.awt.Color(199, 227, 255));
        TField_ClientPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientPhoneNumberActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(TField_ClientPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 295, 180, 20));

        TField_ClientAdress.setBackground(new java.awt.Color(199, 227, 255));
        TField_ClientAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TField_ClientAdressActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(TField_ClientAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 337, 180, 20));

        Btn_ModifyClient.setBackground(new java.awt.Color(108, 169, 230));
        Btn_ModifyClient.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        Btn_ModifyClient.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ModifyClient.setText("Modificar");
        IntFrame_ClientsAdminConfig.getContentPane().add(Btn_ModifyClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 210, 70));

        Btn_DeleteClient.setBackground(new java.awt.Color(108, 169, 230));
        Btn_DeleteClient.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        Btn_DeleteClient.setForeground(new java.awt.Color(255, 255, 255));
        Btn_DeleteClient.setText("Eliminar");
        Btn_DeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteClientActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(Btn_DeleteClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 210, 70));

        Lbl_Bg_ClientsAdminConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/Modificarcliente.png"))); // NOI18N
        IntFrame_ClientsAdminConfig.getContentPane().add(Lbl_Bg_ClientsAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        IntFrame_AdminView.getContentPane().add(IntFrame_ClientsAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_ClientsAdminConfig.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_SalesAdminConfig.setClosable(true);
        IntFrame_SalesAdminConfig.setTitle("Administrador de ventas");
        IntFrame_SalesAdminConfig.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_SalesAdminConfig.setLayer(1);
        IntFrame_SalesAdminConfig.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_SalesAdminConfig.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_SalesAdminConfig.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_SalesAdminConfig.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_SalesAdminConfig.setVisible(false);
        IntFrame_SalesAdminConfig.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_SalesAdminConfigInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_SalesAdminConfig.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        IntFrame_AdminView.getContentPane().add(IntFrame_SalesAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_SalesAdminConfig.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        Btn_Back_AdminView.setBackground(new java.awt.Color(108, 169, 230));
        Btn_Back_AdminView.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Btn_Back_AdminView.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Back_AdminView.setText("Regresar a cliente");
        Btn_Back_AdminView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Back_AdminViewActionPerformed(evt);
            }
        });
        IntFrame_AdminView.getContentPane().add(Btn_Back_AdminView, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 150, 40));

        Lbl_Entry_CarsAdminConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_Entry_CarsAdminConfigMouseClicked(evt);
            }
        });
        IntFrame_AdminView.getContentPane().add(Lbl_Entry_CarsAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 230, 270));

        Lbl_Entry_ClientsAdminConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_Entry_ClientsAdminConfigMouseClicked(evt);
            }
        });
        IntFrame_AdminView.getContentPane().add(Lbl_Entry_ClientsAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 230, 270));

        Lbl_Entry_SalesAdminConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_Entry_SalesAdminConfigMouseClicked(evt);
            }
        });
        IntFrame_AdminView.getContentPane().add(Lbl_Entry_SalesAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 220, 260));

        Lbl_Bg_AdminView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/Servicios.png"))); // NOI18N
        IntFrame_AdminView.getContentPane().add(Lbl_Bg_AdminView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 510));

        getContentPane().add(IntFrame_AdminView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));
        try {
            IntFrame_AdminView.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jMenu2.setText("CarCrafter");

        jMenuItemAcercade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAcercade.setText("Acerca de");
        jMenuItemAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercadeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAcercade);

        jMenuItemInstrucciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemInstrucciones.setText("Instrucciones");
        jMenu2.add(jMenuItemInstrucciones);

        jMenuBarAcercade.add(jMenu2);

        setJMenuBar(jMenuBarAcercade);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Eventos de formulario
     */
    //Evento de Btn_ConfirmPasswordChange para Autenticar cambio de contraseña
    private void Btn_ConfirmPasswordChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConfirmPasswordChangeActionPerformed
        String Last = String.valueOf(Pfield_LastPassword.getPassword());
        String New = String.valueOf(Pfield_NewPassword.getPassword());
        String Confirm = String.valueOf(Pfield_ConfirmNewPassword.getPassword());
        TheMagic.AutenticatePasswordChange(Last, New, Confirm);
    }//GEN-LAST:event_Btn_ConfirmPasswordChangeActionPerformed

    //Evento de Btn_BackChangePassword para regresar a AdminLogin
    private void Btn_BackChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BackChangePasswordActionPerformed
        //Borrar los campos del cambio
        Pfield_LastPassword.setText("");
        Pfield_NewPassword.setText("");
        Pfield_ConfirmNewPassword.setText("");
        //Volver al login de administrador
        IntFrame_PasswordChange.setVisible(false);
        IntFrame_AdminLogin.setVisible(true);
    }//GEN-LAST:event_Btn_BackChangePasswordActionPerformed

    //Evento al cerrar IntFrame_CarsAdminConfig para volver a AdminView
    private void IntFrame_CarsAdminConfigInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_CarsAdminConfigInternalFrameClosed
        IntFrame_ClientView.setVisible(false);
        IntFrame_AdminView.setVisible(true);
    }//GEN-LAST:event_IntFrame_CarsAdminConfigInternalFrameClosed

    //Evento al cerrar IntFrame_ClientsAdminConfig para volver a AdminView
    private void IntFrame_ClientsAdminConfigInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_ClientsAdminConfigInternalFrameClosed
        IntFrame_ClientView.setVisible(false);
        IntFrame_AdminView.setVisible(true);
    }//GEN-LAST:event_IntFrame_ClientsAdminConfigInternalFrameClosed

    //Evento al cerrar IntFrame_SalesAdminConfig para volver a AdminView
    private void IntFrame_SalesAdminConfigInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_SalesAdminConfigInternalFrameClosed
        IntFrame_ClientView.setVisible(false);
        IntFrame_AdminView.setVisible(true);
    }//GEN-LAST:event_IntFrame_SalesAdminConfigInternalFrameClosed

    //Evento de Lbl_AdminEntry para entrar al Admin Login
    private void Lbl_AdminEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_AdminEntryMouseClicked
        IntFrame_AdminLogin.setVisible(true);
    }//GEN-LAST:event_Lbl_AdminEntryMouseClicked

    //Evento de Btn_Back_AdminView para volver a la vista de cliente
    private void Btn_Back_AdminViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Back_AdminViewActionPerformed
        IntFrame_ClientView.setVisible(true);
        IntFrame_AdminView.setVisible(false);
    }//GEN-LAST:event_Btn_Back_AdminViewActionPerformed

    private void Pfield_ConfirmNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pfield_ConfirmNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pfield_ConfirmNewPasswordActionPerformed

    private void Pfield_NewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pfield_NewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pfield_NewPasswordActionPerformed

    private void Pfield_LastPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pfield_LastPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pfield_LastPasswordActionPerformed

    private void Lbl_Entry_CarsAdminConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_Entry_CarsAdminConfigMouseClicked
        IntFrame_CarsAdminConfig.setVisible(true);
    }//GEN-LAST:event_Lbl_Entry_CarsAdminConfigMouseClicked

    private void Lbl_Entry_ClientsAdminConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_Entry_ClientsAdminConfigMouseClicked
        IntFrame_ClientsAdminConfig.setVisible(true);
    }//GEN-LAST:event_Lbl_Entry_ClientsAdminConfigMouseClicked

    private void Lbl_Entry_SalesAdminConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_Entry_SalesAdminConfigMouseClicked
        IntFrame_SalesAdminConfig.setVisible(true);
    }//GEN-LAST:event_Lbl_Entry_SalesAdminConfigMouseClicked

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        String placa = jTextFieldPlaca1.getText();

        // Realiza la validación de si esta vacia el field de la placa
        if (placa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una placa válida para modificar un auto.");
            return;
        }
        // Bucle para buscar el carro con la placa
        boolean carroEncontrado = false;
        for (Autos auto : automobileRecords) {
            if (auto.getPlaca().equalsIgnoreCase(placa)) {
                carroEncontrado = true;

                // leee valores de campos de entrada
                String color = jTextFieldColor.getText().toLowerCase();
                String marca = jTextFieldMarca.getText().toLowerCase();
                String nombreModelo = jTextFieldPrecioModelo.getText().toLowerCase();
                String añoLanzamientoStr = jTextFieldAño.getText();
                String precioCompraStr = jTextFieldPrecioCompra.getText().replace(',', '.');
                String precioVentaStr = jTextFieldPreciodeVenta.getText().replace(',', '.');

                // Actualiza los campos del automóvil solo si no están vacíos
                if (!color.isEmpty()) {
                    auto.setColor(color);
                }
                if (!marca.isEmpty()) {
                    String[] modeloParts = auto.getModelo().split(",");
                    auto.setModelo(marca + "," + modeloParts[1] + "," + modeloParts[2]);
                }
                if (!nombreModelo.isEmpty()) {
                    String[] modeloParts = auto.getModelo().split(",");
                    auto.setModelo(modeloParts[0] + "," + nombreModelo + "," + modeloParts[2]);
                }
                if (!añoLanzamientoStr.isEmpty()) {
                    try {
                        int añoLanzamiento = Integer.parseInt(añoLanzamientoStr);
                        String[] modeloParts = auto.getModelo().split(",");
                        auto.setModelo(modeloParts[0] + "," + modeloParts[1] + "," + añoLanzamiento);
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Año de Lanzamiento debe ser válido.");
                    }
                }
                if (!precioCompraStr.isEmpty()) {
                    try {
                        double precioCompra = Double.parseDouble(precioCompraStr);
                        auto.setPrecioDeCompra(precioCompra);
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Precio de Compra debe ser válido.");
                    }
                }
                if (!precioVentaStr.isEmpty()) {
                    try {
                        double precioVenta = Double.parseDouble(precioVentaStr);
                        auto.setPrecioDeVenta(precioVenta);
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Precio de Venta debe ser válido.");
                    }
                }

                JOptionPane.showMessageDialog(this, "Datos del auto con placa " + placa + " modificados con éxito.");
                break; // Salir del bucle después de modificar el automóvil
            }
        }
        // Si no se encontró el automóvil
        if (!carroEncontrado) {
            JOptionPane.showMessageDialog(this, "No se encontró un auto con la placa " + placa);
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed
    private boolean containsSpecialCharacters(String str) {
        String regex = "^[a-zA-Z0-9.,]+$";
        return !Pattern.matches(regex, str);
    }

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // Leer los datos de los campos y convertirlos a minúsculas
        String placa = jTextFieldPlaca1.getText().toLowerCase();
        String color = jTextFieldColor.getText().toLowerCase();
        String marca = jTextFieldMarca.getText().toLowerCase();
        String nombreModelo = jTextFieldPrecioModelo.getText().toLowerCase();
        String añoLanzamientoStr = jTextFieldAño.getText();
        String precioCompraStr = jTextFieldPrecioCompra.getText().replace(',', '.');
        String precioVentaStr = jTextFieldPreciodeVenta.getText().replace(',', '.');

        // Verificar si ya existe un automóvil con la misma placa
        for (Autos registro : automobileRecords) {
            if (registro.getPlaca().equals(placa)) {
                JOptionPane.showMessageDialog(this, "Ya existe un auto con la misma placa.");
                return;
            }
        }

        String incompleteField = null;

        if (placa.isEmpty()) {
            incompleteField = "Placa";
        } else if (color.isEmpty()) {
            incompleteField = "Color";
        } else if (marca.isEmpty()) {
            incompleteField = "Marca";
        } else if (nombreModelo.isEmpty()) {
            incompleteField = "Nombre del Modelo";
        } else if (añoLanzamientoStr.isEmpty()) {
            incompleteField = "Año de Lanzamiento";
        } else if (precioCompraStr.isEmpty()) {
            incompleteField = "Precio de Compra";
        } else if (precioVentaStr.isEmpty()) {
            incompleteField = "Precio de Venta";
        }

        if (incompleteField != null) {
            JOptionPane.showMessageDialog(this, "El campo '" + incompleteField + "' está incompleto.");
            return;
        }

        if (containsSpecialCharacters(placa) || containsSpecialCharacters(color)
                || containsSpecialCharacters(marca) || containsSpecialCharacters(nombreModelo)
                || containsSpecialCharacters(añoLanzamientoStr) || containsSpecialCharacters(precioCompraStr)
                || containsSpecialCharacters(precioVentaStr)) {
            JOptionPane.showMessageDialog(this, "Campos contienen caracteres especiales.");
            return;
        }

        int añoLanzamiento;
        double precioCompra;
        double precioVenta;

        try {
            añoLanzamiento = Integer.parseInt(añoLanzamientoStr);
            precioCompra = Double.parseDouble(precioCompraStr);
            precioVenta = Double.parseDouble(precioVentaStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Año de Lanzamiento, Precio de Compra y Precio de Venta deben ser válidos.");
            return;
        }

        // Concatenar la información de los campos para dejarlo único en el modelo
        String modelostr = marca + "," + nombreModelo + "," + añoLanzamiento;

        // Crear un objeto de tipo Autos con la información
        Autos registro = new Autos();
        registro.setPlaca(placa);
        registro.setColor(color);
        registro.setModelo(modelostr);
        registro.setPrecioDeCompra(precioCompra);
        registro.setPrecioDeVenta(precioVenta);

        // Agregar el registro a la lista de automóviles
        automobileRecords.add(registro);

        // Limpiar los campos de entrada y mostrar un mensaje de éxito
        jTextFieldPlaca1.setText("");
        jTextFieldColor.setText("");
        jTextFieldMarca.setText("");
        jTextFieldPrecioModelo.setText("");
        jTextFieldAño.setText("");
        jTextFieldPrecioCompra.setText("");
        jTextFieldPreciodeVenta.setText("");

        JOptionPane.showMessageDialog(this, "Registro exitoso");
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jTextFieldPlaca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaca1ActionPerformed

    private void jTextFieldColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColorActionPerformed

    private void jTextFieldPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioCompraActionPerformed

    private void Btn_DeleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_DeleteClientActionPerformed

    private void TField_ClientIdentificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientIdentificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientIdentificationActionPerformed

    private void TField_ClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientNameActionPerformed

    private void TField_ClientLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientLastnameActionPerformed

    private void TField_ClientBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientBirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientBirthdayActionPerformed

    private void TField_CLientEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_CLientEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_CLientEmailActionPerformed

    private void TField_ClientPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientPhoneNumberActionPerformed

    private void TField_ClientAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientAdressActionPerformed

    private void jTextFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMarcaActionPerformed

    private void jTextFieldAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAñoActionPerformed

    private void jTextFieldPrecioModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioModeloActionPerformed

    private void jTextFieldPreciodeVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPreciodeVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPreciodeVentaActionPerformed

    private void TField_ClientAdress_BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientAdress_BuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientAdress_BuyActionPerformed

    private void TField_ClientPhoneNumber_BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientPhoneNumber_BuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientPhoneNumber_BuyActionPerformed

    private void TField_ClientEmail_BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientEmail_BuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientEmail_BuyActionPerformed

    private void TField_ClientBirthday_BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientBirthday_BuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientBirthday_BuyActionPerformed

    private void TField_ClientLastname_BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientLastname_BuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientLastname_BuyActionPerformed

    private void TField_ClientName_BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientName_BuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientName_BuyActionPerformed

    private void TField_ClientIdentification_BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TField_ClientIdentification_BuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TField_ClientIdentification_BuyActionPerformed

    private void Btn_BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_BuyActionPerformed

    //Evento al cerrar IntFrame_AdminLogin para volver a ClientView
    private void IntFrame_AdminLoginInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_AdminLoginInternalFrameClosed
        IntFrame_AdminView.setVisible(false);
        IntFrame_ClientView.setVisible(true);
    }//GEN-LAST:event_IntFrame_AdminLoginInternalFrameClosed

    //Evento de Btn_ExitAdminLogin para regresar a ClientView 
    private void Button_ExitAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExitAdminLoginActionPerformed
        IntFrame_AdminLogin.setVisible(false);
        IntFrame_ClientView.setVisible(true);
    }//GEN-LAST:event_Button_ExitAdminLoginActionPerformed

    //Evento de Lbl_PasswordChange para llegar al menu de cambio de contraseña
    private void Lbl_PasswordChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_PasswordChangeMouseClicked
        Pfield_AdminPassword.setText("");
        IntFrame_AdminLogin.setVisible(false);
        IntFrame_PasswordChange.setVisible(true);
    }//GEN-LAST:event_Lbl_PasswordChangeMouseClicked

    //Evento de Btn_ConfirmAdminLogin para autenticar inicio de sesion
    private void Btn_ConfirmAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConfirmAdminLoginActionPerformed
        Admin GenCredentials = new Admin();
        GenCredentials.setUser(Tfield_AdminUser.getText());
        GenCredentials.setPassword(String.valueOf(Pfield_AdminPassword.getPassword()));
        TheMagic.Autentication(GenCredentials);
    }//GEN-LAST:event_Btn_ConfirmAdminLoginActionPerformed

    private void Tfield_AdminUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tfield_AdminUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tfield_AdminUserActionPerformed

    private void Pfield_AdminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pfield_AdminPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pfield_AdminPasswordActionPerformed


    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        String placa = jTextFieldPlaca1.getText();
        EliminarPorPlaca(placa);
        jTextFieldPlaca1.setText("");
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jMenuItemAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAcercadeActionPerformed
    private void EliminarPorPlaca(String placa) {
        for (Autos registro : automobileRecords) {
            if (registro.getPlaca().equals(placa)) {
                automobileRecords.remove(registro);
                JOptionPane.showMessageDialog(this, "Auto con placa " + placa + " eliminado.");
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "No se encontró un auto con la placa " + placa);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BackChangePassword;
    private javax.swing.JButton Btn_Back_AdminView;
    private javax.swing.JButton Btn_Buy;
    private javax.swing.JButton Btn_ConfirmAdminLogin;
    private javax.swing.JButton Btn_ConfirmPasswordChange;
    private javax.swing.JButton Btn_DeleteClient;
    private javax.swing.JButton Btn_ModifyClient;
    private javax.swing.JButton Button_ExitAdminLogin;
    public static javax.swing.JInternalFrame IntFrame_AdminLogin;
    public static javax.swing.JInternalFrame IntFrame_AdminView;
    private javax.swing.JInternalFrame IntFrame_BuyACar;
    public static javax.swing.JInternalFrame IntFrame_CarsAdminConfig;
    public static javax.swing.JInternalFrame IntFrame_ClientView;
    public static javax.swing.JInternalFrame IntFrame_ClientsAdminConfig;
    public static javax.swing.JInternalFrame IntFrame_PasswordChange;
    public static javax.swing.JInternalFrame IntFrame_SalesAdminConfig;
    private javax.swing.JLabel Lbl_AdminEntry;
    private javax.swing.JLabel Lbl_Bg_AdminLogin;
    private javax.swing.JLabel Lbl_Bg_AdminView;
    private javax.swing.JLabel Lbl_Bg_BuyACar;
    private javax.swing.JLabel Lbl_Bg_CarsAdminConfig;
    private javax.swing.JLabel Lbl_Bg_ClientView;
    private javax.swing.JLabel Lbl_Bg_ClientsAdminConfig;
    private javax.swing.JLabel Lbl_Bg_PasswordChange;
    private javax.swing.JLabel Lbl_CarInfo;
    private javax.swing.JLabel Lbl_Entry_CarsAdminConfig;
    private javax.swing.JLabel Lbl_Entry_ClientsAdminConfig;
    private javax.swing.JLabel Lbl_Entry_SalesAdminConfig;
    private javax.swing.JLabel Lbl_PasswordChange;
    public static javax.swing.JLabel Lbl_PopUp_Base;
    public static javax.swing.JPasswordField Pfield_AdminPassword;
    public static javax.swing.JPasswordField Pfield_ConfirmNewPassword;
    public static javax.swing.JPasswordField Pfield_LastPassword;
    public static javax.swing.JPasswordField Pfield_NewPassword;
    public static javax.swing.JDialog PopUp_AdminLogin;
    private javax.swing.JScrollPane Scroll_Table_CarsList;
    private javax.swing.JTextField TField_CLientEmail;
    private javax.swing.JTextField TField_ClientAdress;
    private javax.swing.JTextField TField_ClientAdress_Buy;
    private javax.swing.JTextField TField_ClientBirthday;
    private javax.swing.JTextField TField_ClientBirthday_Buy;
    private javax.swing.JTextField TField_ClientEmail_Buy;
    private javax.swing.JTextField TField_ClientIdentification;
    private javax.swing.JTextField TField_ClientIdentification_Buy;
    private javax.swing.JTextField TField_ClientLastname;
    private javax.swing.JTextField TField_ClientLastname_Buy;
    private javax.swing.JTextField TField_ClientName;
    private javax.swing.JTextField TField_ClientName_Buy;
    private javax.swing.JTextField TField_ClientPhoneNumber;
    private javax.swing.JTextField TField_ClientPhoneNumber_Buy;
    private javax.swing.JTable Table_CarsList;
    private javax.swing.JTextField Tfield_AdminUser;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBarAcercade;
    private javax.swing.JMenuItem jMenuItemAcercade;
    private javax.swing.JMenuItem jMenuItemInstrucciones;
    private javax.swing.JTextField jTextFieldAño;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldPlaca1;
    private javax.swing.JTextField jTextFieldPrecioCompra;
    private javax.swing.JTextField jTextFieldPrecioModelo;
    private javax.swing.JTextField jTextFieldPreciodeVenta;
    // End of variables declaration//GEN-END:variables

}
