package laboratorio2.FrontEnd;

import laboratorio2.BackEnd.Admin;
import laboratorio2.BackEnd.TheMagic;

public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopUp_AdminLogin = new javax.swing.JDialog();
        Lbl_PopUp_Base = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        IntFrame_PasswordChange = new javax.swing.JInternalFrame();
        Pfield_LastPassword = new javax.swing.JPasswordField();
        Pfield_NewPassword = new javax.swing.JPasswordField();
        Pfield_ConfirmNewPassword = new javax.swing.JPasswordField();
        Btn_ConfirmPasswordChange = new javax.swing.JButton();
        Btn_BackChangePassword = new javax.swing.JButton();
        Lbl_Bg_PasswordChange = new javax.swing.JLabel();
        IntFrame_AdminLogin = new javax.swing.JInternalFrame();
        Pfield_AdminPassword = new javax.swing.JPasswordField();
        Tfield_AdminUser = new javax.swing.JTextField();
        Btn_ConfirmAdminLogin = new javax.swing.JButton();
        Lbl_PasswordChange = new javax.swing.JLabel();
        Button_ExitAdminLogin = new javax.swing.JButton();
        Lbl_Bg_AdminLogin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        IntFrame_ClientView = new javax.swing.JInternalFrame();
        IntFrame_BuyACar = new javax.swing.JInternalFrame();
        Btn_Buy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDireccion1 = new javax.swing.JTextField();
        jTextFieldCelular1 = new javax.swing.JTextField();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jTextFieldFechaNac1 = new javax.swing.JTextField();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jTextFieldIdentificacion1 = new javax.swing.JTextField();
        Lbl_Bg_BuyACar = new javax.swing.JLabel();
        Scroll_Table_CarsList = new javax.swing.JScrollPane();
        Table_CarsList = new javax.swing.JTable();
        Lbl_AdminEntry = new javax.swing.JLabel();
        Lbl_Bg_ClientView = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        IntFrame_AdminView = new javax.swing.JInternalFrame();
        IntFrame_CarsAdminConfig = new javax.swing.JInternalFrame();
        jButtonModificar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jTextFieldPrecioModelo = new javax.swing.JTextField();
        jTextFieldPreciodeVenta = new javax.swing.JTextField();
        jTextFieldAño = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldPrecioCompra = new javax.swing.JTextField();
        jTextFieldColor = new javax.swing.JTextField();
        jTextFieldPlaca1 = new javax.swing.JTextField();
        jLabelFindo = new javax.swing.JLabel();
        IntFrame_ClientsAdminConfig = new javax.swing.JInternalFrame();
        jButtonModificarClient = new javax.swing.JButton();
        jButtonEliminarClient = new javax.swing.JButton();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldFechaNac = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jLabelFondoRegisCliente = new javax.swing.JLabel();
        IntFrame_SalesAdminConfig = new javax.swing.JInternalFrame();
        Btn_Back_AdminView = new javax.swing.JButton();
        jLabelAutos = new javax.swing.JLabel();
        jLabelVentas = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        PopUp_AdminLogin.setAlwaysOnTop(true);
        PopUp_AdminLogin.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        PopUp_AdminLogin.setIconImage(null);
        PopUp_AdminLogin.setIconImages(null);
        PopUp_AdminLogin.setLocation(IntFrame_AdminLogin.location());
        PopUp_AdminLogin.setMinimumSize(new java.awt.Dimension(300, 300));
        PopUp_AdminLogin.setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        PopUp_AdminLogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_PopUp_Base.setMaximumSize(new java.awt.Dimension(300, 300));
        Lbl_PopUp_Base.setMinimumSize(new java.awt.Dimension(300, 300));
        Lbl_PopUp_Base.setPreferredSize(new java.awt.Dimension(300, 300));
        PopUp_AdminLogin.getContentPane().add(Lbl_PopUp_Base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 300));

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prototype 1");
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(720, 440));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IntFrame_PasswordChange.setClosable(true);
        IntFrame_PasswordChange.setTitle("Cambio de contraseña");
        IntFrame_PasswordChange.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_PasswordChange.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_PasswordChange.setLayer(2);
        IntFrame_PasswordChange.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_PasswordChange.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_PasswordChange.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_PasswordChange.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_PasswordChange.setVisible(false);
        IntFrame_PasswordChange.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pfield_LastPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pfield_LastPasswordActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Pfield_LastPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 210, -1));

        Pfield_NewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pfield_NewPasswordActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Pfield_NewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 210, -1));

        Pfield_ConfirmNewPassword.setAlignmentX(0.2F);
        Pfield_ConfirmNewPassword.setAlignmentY(0.1F);
        Pfield_ConfirmNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pfield_ConfirmNewPasswordActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Pfield_ConfirmNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 210, -1));

        Btn_ConfirmPasswordChange.setBackground(new java.awt.Color(108, 169, 230));
        Btn_ConfirmPasswordChange.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Btn_ConfirmPasswordChange.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ConfirmPasswordChange.setText("Confirmar");
        Btn_ConfirmPasswordChange.setToolTipText("");
        Btn_ConfirmPasswordChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConfirmPasswordChangeActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Btn_ConfirmPasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 100, -1));

        Btn_BackChangePassword.setBackground(new java.awt.Color(108, 169, 230));
        Btn_BackChangePassword.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Btn_BackChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        Btn_BackChangePassword.setText("Atras");
        Btn_BackChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BackChangePasswordActionPerformed(evt);
            }
        });
        IntFrame_PasswordChange.getContentPane().add(Btn_BackChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 100, 30));

        Lbl_Bg_PasswordChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/CambiarContraseña.png"))); // NOI18N
        IntFrame_PasswordChange.getContentPane().add(Lbl_Bg_PasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 380));

        getContentPane().add(IntFrame_PasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_PasswordChange.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_AdminLogin.setClosable(true);
        IntFrame_AdminLogin.setTitle("Iniciar Sesión");
        IntFrame_AdminLogin.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_AdminLogin.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_AdminLogin.setLayer(1);
        IntFrame_AdminLogin.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_AdminLogin.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_AdminLogin.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_AdminLogin.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_AdminLogin.setVisible(true);
        IntFrame_AdminLogin.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_AdminLoginInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_AdminLogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pfield_AdminPassword.setBackground(new java.awt.Color(199, 227, 255));
        Pfield_AdminPassword.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Pfield_AdminPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pfield_AdminPasswordActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Pfield_AdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 185, 180, 25));

        Tfield_AdminUser.setBackground(new java.awt.Color(199, 227, 255));
        Tfield_AdminUser.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Tfield_AdminUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tfield_AdminUserActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Tfield_AdminUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 141, 180, 25));

        Btn_ConfirmAdminLogin.setBackground(new java.awt.Color(108, 169, 230));
        Btn_ConfirmAdminLogin.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        Btn_ConfirmAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        Btn_ConfirmAdminLogin.setText("Ingresar");
        Btn_ConfirmAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConfirmAdminLoginActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Btn_ConfirmAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, 30));

        Lbl_PasswordChange.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        Lbl_PasswordChange.setForeground(new java.awt.Color(44, 131, 218));
        Lbl_PasswordChange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_PasswordChange.setText("CAMBIAR CONTRASEÑA");
        Lbl_PasswordChange.setToolTipText("");
        Lbl_PasswordChange.setAlignmentY(0.0F);
        Lbl_PasswordChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_PasswordChangeMouseClicked(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Lbl_PasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 200, 30));

        Button_ExitAdminLogin.setBackground(new java.awt.Color(108, 169, 230));
        Button_ExitAdminLogin.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        Button_ExitAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        Button_ExitAdminLogin.setText("Salir");
        Button_ExitAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExitAdminLoginActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Button_ExitAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 100, 30));

        Lbl_Bg_AdminLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/Fondo-Login.png"))); // NOI18N
        IntFrame_AdminLogin.getContentPane().add(Lbl_Bg_AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));
        IntFrame_AdminLogin.setJMenuBar(jMenuBar1);

        getContentPane().add(IntFrame_AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_AdminLogin.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_ClientView.setTitle("Vista de cliente");
        IntFrame_ClientView.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_ClientView.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_ClientView.setMaximumSize(new java.awt.Dimension(960, 540));
        IntFrame_ClientView.setMinimumSize(new java.awt.Dimension(960, 540));
        IntFrame_ClientView.setPreferredSize(new java.awt.Dimension(960, 540));
        try {
            IntFrame_ClientView.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_ClientView.setVisible(true);
        IntFrame_ClientView.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IntFrame_BuyACar.setClosable(true);
        IntFrame_BuyACar.setTitle("Menú de compra");
        IntFrame_BuyACar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_BuyACar.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_BuyACar.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_BuyACar.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_BuyACar.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_BuyACar.setVisible(false);
        IntFrame_BuyACar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Buy.setBackground(new java.awt.Color(108, 169, 230));
        Btn_Buy.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        Btn_Buy.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Buy.setText("Comprar");
        Btn_Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuyActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(Btn_Buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 170, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("*Aqui se muetran los datos del auto que se va a comprar*");
        IntFrame_BuyACar.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 270, 200));

        jTextFieldDireccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccion1ActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(jTextFieldDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 180, 20));

        jTextFieldCelular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCelular1ActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(jTextFieldCelular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 180, 20));

        jTextFieldEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmail1ActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(jTextFieldEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 180, 20));

        jTextFieldFechaNac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac1ActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(jTextFieldFechaNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, 20));

        jTextFieldApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellido1ActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(jTextFieldApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, 20));

        jTextFieldNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombre1ActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(jTextFieldNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 180, 20));

        jTextFieldIdentificacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificacion1ActionPerformed(evt);
            }
        });
        IntFrame_BuyACar.getContentPane().add(jTextFieldIdentificacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 180, 20));

        Lbl_Bg_BuyACar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/RegistrarClientes.png"))); // NOI18N
        IntFrame_BuyACar.getContentPane().add(Lbl_Bg_BuyACar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        IntFrame_ClientView.getContentPane().add(IntFrame_BuyACar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_BuyACar.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        Scroll_Table_CarsList.setMaximumSize(new java.awt.Dimension(560, 400));
        Scroll_Table_CarsList.setMinimumSize(new java.awt.Dimension(560, 400));
        Scroll_Table_CarsList.setPreferredSize(new java.awt.Dimension(560, 400));

        Table_CarsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_CarsList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        Table_CarsList.setMaximumSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setMinimumSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setPreferredSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setShowGrid(false);
        Scroll_Table_CarsList.setViewportView(Table_CarsList);

        IntFrame_ClientView.getContentPane().add(Scroll_Table_CarsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 560, 400));

        Lbl_AdminEntry.setText("Entrar a las opciones de administrador");
        Lbl_AdminEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_AdminEntryMouseClicked(evt);
            }
        });
        IntFrame_ClientView.getContentPane().add(Lbl_AdminEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 310, -1));

        Lbl_Bg_ClientView.setMaximumSize(new java.awt.Dimension(960, 510));
        Lbl_Bg_ClientView.setMinimumSize(new java.awt.Dimension(960, 510));
        Lbl_Bg_ClientView.setPreferredSize(new java.awt.Dimension(960, 510));
        IntFrame_ClientView.getContentPane().add(Lbl_Bg_ClientView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 510));

        jMenu4.setText("CarCrafter");

        jMenuItem1.setText("jMenuItem1");
        jMenu4.add(jMenuItem1);

        jMenuBar2.add(jMenu4);

        IntFrame_ClientView.setJMenuBar(jMenuBar2);

        getContentPane().add(IntFrame_ClientView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));
        try {
            IntFrame_ClientView.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_AdminView.setTitle("Vista de administrador");
        IntFrame_AdminView.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_AdminView.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_AdminView.setMaximumSize(new java.awt.Dimension(960, 540));
        IntFrame_AdminView.setMinimumSize(new java.awt.Dimension(960, 540));
        IntFrame_AdminView.setPreferredSize(new java.awt.Dimension(960, 540));
        try {
            IntFrame_AdminView.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_AdminView.setVisible(false);
        IntFrame_AdminView.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IntFrame_CarsAdminConfig.setClosable(true);
        IntFrame_CarsAdminConfig.setTitle("Administrador de autos");
        IntFrame_CarsAdminConfig.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_CarsAdminConfig.setLayer(1);
        IntFrame_CarsAdminConfig.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_CarsAdminConfig.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_CarsAdminConfig.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_CarsAdminConfig.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_CarsAdminConfig.setVisible(false);
        IntFrame_CarsAdminConfig.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_CarsAdminConfigInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonModificar.setBackground(new java.awt.Color(108, 169, 230));
        jButtonModificar.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 180, 60));

        jButtonRegistrar.setBackground(new java.awt.Color(108, 169, 230));
        jButtonRegistrar.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 180, 60));

        jButtonEliminar.setBackground(new java.awt.Color(108, 169, 230));
        jButtonEliminar.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar");
        IntFrame_CarsAdminConfig.getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 180, 60));

        jTextFieldPrecioModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioModeloActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldPrecioModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 210, -1));

        jTextFieldPreciodeVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPreciodeVentaActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldPreciodeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 210, -1));

        jTextFieldAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAñoActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 247, 210, -1));

        jTextFieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMarcaActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 210, -1));

        jTextFieldPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioCompraActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 283, 210, 30));

        jTextFieldColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColorActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 210, 30));

        jTextFieldPlaca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaca1ActionPerformed(evt);
            }
        });
        IntFrame_CarsAdminConfig.getContentPane().add(jTextFieldPlaca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 210, -1));

        jLabelFindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/RegistroAutoFin.png"))); // NOI18N
        IntFrame_CarsAdminConfig.getContentPane().add(jLabelFindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 360));

        IntFrame_AdminView.getContentPane().add(IntFrame_CarsAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_CarsAdminConfig.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_ClientsAdminConfig.setClosable(true);
        IntFrame_ClientsAdminConfig.setTitle("Administrador de Clientes");
        IntFrame_ClientsAdminConfig.setToolTipText("");
        IntFrame_ClientsAdminConfig.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_ClientsAdminConfig.setLayer(1);
        IntFrame_ClientsAdminConfig.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_ClientsAdminConfig.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_ClientsAdminConfig.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_ClientsAdminConfig.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_ClientsAdminConfig.setVisible(false);
        IntFrame_ClientsAdminConfig.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_ClientsAdminConfigInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonModificarClient.setBackground(new java.awt.Color(108, 169, 230));
        jButtonModificarClient.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jButtonModificarClient.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarClient.setText("Modificar");
        IntFrame_ClientsAdminConfig.getContentPane().add(jButtonModificarClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 210, 70));

        jButtonEliminarClient.setBackground(new java.awt.Color(108, 169, 230));
        jButtonEliminarClient.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jButtonEliminarClient.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminarClient.setText("Eliminar");
        jButtonEliminarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarClientActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(jButtonEliminarClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 210, 70));

        jTextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccionActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 180, 20));

        jTextFieldCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCelularActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(jTextFieldCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 180, 20));

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 180, 20));

        jTextFieldFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNacActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(jTextFieldFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, 20));

        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 180, 20));

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 180, 20));

        jTextFieldIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdentificacionActionPerformed(evt);
            }
        });
        IntFrame_ClientsAdminConfig.getContentPane().add(jTextFieldIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 180, 20));

        jLabelFondoRegisCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/Eliminar:Modificarcliente.png"))); // NOI18N
        IntFrame_ClientsAdminConfig.getContentPane().add(jLabelFondoRegisCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        IntFrame_AdminView.getContentPane().add(IntFrame_ClientsAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_ClientsAdminConfig.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_SalesAdminConfig.setClosable(true);
        IntFrame_SalesAdminConfig.setTitle("Administrador de ventas");
        IntFrame_SalesAdminConfig.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/logo carcrafter 40x40.png"))); // NOI18N
        IntFrame_SalesAdminConfig.setLayer(1);
        IntFrame_SalesAdminConfig.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_SalesAdminConfig.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_SalesAdminConfig.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_SalesAdminConfig.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_SalesAdminConfig.setVisible(false);
        IntFrame_SalesAdminConfig.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_SalesAdminConfigInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_SalesAdminConfig.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        IntFrame_AdminView.getContentPane().add(IntFrame_SalesAdminConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_SalesAdminConfig.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        Btn_Back_AdminView.setBackground(new java.awt.Color(108, 169, 230));
        Btn_Back_AdminView.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Btn_Back_AdminView.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Back_AdminView.setText("Regresar a cliente");
        Btn_Back_AdminView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Back_AdminViewActionPerformed(evt);
            }
        });
        IntFrame_AdminView.getContentPane().add(Btn_Back_AdminView, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 150, 40));

        jLabelAutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAutosMouseClicked(evt);
            }
        });
        IntFrame_AdminView.getContentPane().add(jLabelAutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 230, 270));

        jLabelVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentasMouseClicked(evt);
            }
        });
        IntFrame_AdminView.getContentPane().add(jLabelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 220, 260));

        jLabelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientesMouseClicked(evt);
            }
        });
        IntFrame_AdminView.getContentPane().add(jLabelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 230, 270));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/Servicios.png"))); // NOI18N
        IntFrame_AdminView.getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 510));

        getContentPane().add(IntFrame_AdminView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));
        try {
            IntFrame_AdminView.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Eventos de formulario
     */
    //Evento de Btn_ConfirmPasswordChange para Autenticar cambio de contraseña
    private void Btn_ConfirmPasswordChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConfirmPasswordChangeActionPerformed
        String Last = String.valueOf(Pfield_LastPassword.getPassword());
        String New = String.valueOf(Pfield_NewPassword.getPassword());
        String Confirm = String.valueOf(Pfield_ConfirmNewPassword.getPassword());
        TheMagic.AutenticatePasswordChange(Last, New, Confirm);
    }//GEN-LAST:event_Btn_ConfirmPasswordChangeActionPerformed

    //Evento de Btn_BackChangePassword para regresar a AdminLogin
    private void Btn_BackChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BackChangePasswordActionPerformed
        //Borrar los campos del cambio
        Pfield_LastPassword.setText("");
        Pfield_NewPassword.setText("");
        Pfield_ConfirmNewPassword.setText("");
        //Volver al login de administrador
        IntFrame_PasswordChange.setVisible(false);
        IntFrame_AdminLogin.setVisible(true);
    }//GEN-LAST:event_Btn_BackChangePasswordActionPerformed

    //Evento al cerrar IntFrame_CarsAdminConfig para volver a AdminView
    private void IntFrame_CarsAdminConfigInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_CarsAdminConfigInternalFrameClosed
        IntFrame_ClientView.setVisible(false);
        IntFrame_AdminView.setVisible(true);
    }//GEN-LAST:event_IntFrame_CarsAdminConfigInternalFrameClosed

    //Evento al cerrar IntFrame_ClientsAdminConfig para volver a AdminView
    private void IntFrame_ClientsAdminConfigInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_ClientsAdminConfigInternalFrameClosed
        IntFrame_ClientView.setVisible(false);
        IntFrame_AdminView.setVisible(true);
    }//GEN-LAST:event_IntFrame_ClientsAdminConfigInternalFrameClosed

    //Evento al cerrar IntFrame_SalesAdminConfig para volver a AdminView
    private void IntFrame_SalesAdminConfigInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_SalesAdminConfigInternalFrameClosed
        IntFrame_ClientView.setVisible(false);
        IntFrame_AdminView.setVisible(true);
    }//GEN-LAST:event_IntFrame_SalesAdminConfigInternalFrameClosed

    //Evento de Lbl_AdminEntry para entrar al Admin Login
    private void Lbl_AdminEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_AdminEntryMouseClicked
        IntFrame_AdminLogin.setVisible(true);
    }//GEN-LAST:event_Lbl_AdminEntryMouseClicked

    //Evento de Btn_Back_AdminView para volver a la vista de cliente
    private void Btn_Back_AdminViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Back_AdminViewActionPerformed
        IntFrame_ClientView.setVisible(true);
        IntFrame_AdminView.setVisible(false);
    }//GEN-LAST:event_Btn_Back_AdminViewActionPerformed

    private void Pfield_ConfirmNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pfield_ConfirmNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pfield_ConfirmNewPasswordActionPerformed

    private void Pfield_NewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pfield_NewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pfield_NewPasswordActionPerformed

    private void Pfield_LastPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pfield_LastPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pfield_LastPasswordActionPerformed

    private void jLabelAutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAutosMouseClicked
        IntFrame_CarsAdminConfig.setVisible(true);
    }//GEN-LAST:event_jLabelAutosMouseClicked

    private void jLabelClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientesMouseClicked
        IntFrame_ClientsAdminConfig.setVisible(true);
    }//GEN-LAST:event_jLabelClientesMouseClicked

    private void jLabelVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentasMouseClicked
        IntFrame_SalesAdminConfig.setVisible(true);
    }//GEN-LAST:event_jLabelVentasMouseClicked

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jTextFieldPlaca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaca1ActionPerformed

    private void jTextFieldColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColorActionPerformed

    private void jTextFieldPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioCompraActionPerformed

    private void jButtonEliminarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarClientActionPerformed

    private void jTextFieldIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificacionActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jTextFieldFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNacActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCelularActionPerformed

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jTextFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMarcaActionPerformed

    private void jTextFieldAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAñoActionPerformed

    private void jTextFieldPrecioModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioModeloActionPerformed

    private void jTextFieldPreciodeVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPreciodeVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPreciodeVentaActionPerformed

    private void jTextFieldDireccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccion1ActionPerformed

    private void jTextFieldCelular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCelular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCelular1ActionPerformed

    private void jTextFieldEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmail1ActionPerformed

    private void jTextFieldFechaNac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac1ActionPerformed

    private void jTextFieldApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido1ActionPerformed

    private void jTextFieldNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombre1ActionPerformed

    private void jTextFieldIdentificacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdentificacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdentificacion1ActionPerformed

    private void Btn_BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_BuyActionPerformed

    //Evento al cerrar IntFrame_AdminLogin para volver a ClientView
    private void IntFrame_AdminLoginInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_AdminLoginInternalFrameClosed
        IntFrame_AdminView.setVisible(false);
        IntFrame_ClientView.setVisible(true);
    }//GEN-LAST:event_IntFrame_AdminLoginInternalFrameClosed

    //Evento de Btn_ExitAdminLogin para regresar a ClientView 
    private void Button_ExitAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExitAdminLoginActionPerformed
        IntFrame_AdminLogin.setVisible(false);
        IntFrame_ClientView.setVisible(true);
    }//GEN-LAST:event_Button_ExitAdminLoginActionPerformed

    //Evento de Lbl_PasswordChange para llegar al menu de cambio de contraseña
    private void Lbl_PasswordChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_PasswordChangeMouseClicked
        Pfield_AdminPassword.setText("");
        IntFrame_AdminLogin.setVisible(false);
        IntFrame_PasswordChange.setVisible(true);
    }//GEN-LAST:event_Lbl_PasswordChangeMouseClicked

    //Evento de Btn_ConfirmAdminLogin para autenticar inicio de sesion
    private void Btn_ConfirmAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConfirmAdminLoginActionPerformed
        Admin GenCredentials = new Admin();
        GenCredentials.setUser(Tfield_AdminUser.getText());
        GenCredentials.setPassword(String.valueOf(Pfield_AdminPassword.getPassword()));
        TheMagic.Autentication(GenCredentials);
    }//GEN-LAST:event_Btn_ConfirmAdminLoginActionPerformed

    private void Tfield_AdminUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tfield_AdminUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tfield_AdminUserActionPerformed

    private void Pfield_AdminPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pfield_AdminPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pfield_AdminPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_BackChangePassword;
    private javax.swing.JButton Btn_Back_AdminView;
    private javax.swing.JButton Btn_Buy;
    private javax.swing.JButton Btn_ConfirmAdminLogin;
    private javax.swing.JButton Btn_ConfirmPasswordChange;
    private javax.swing.JButton Button_ExitAdminLogin;
    private javax.swing.JInternalFrame IntFrame_AdminLogin;
    public static javax.swing.JInternalFrame IntFrame_AdminView;
    private javax.swing.JInternalFrame IntFrame_BuyACar;
    public static javax.swing.JInternalFrame IntFrame_CarsAdminConfig;
    public static javax.swing.JInternalFrame IntFrame_ClientView;
    public static javax.swing.JInternalFrame IntFrame_ClientsAdminConfig;
    public static javax.swing.JInternalFrame IntFrame_PasswordChange;
    public static javax.swing.JInternalFrame IntFrame_SalesAdminConfig;
    private javax.swing.JLabel Lbl_AdminEntry;
    private javax.swing.JLabel Lbl_Bg_AdminLogin;
    private javax.swing.JLabel Lbl_Bg_BuyACar;
    private javax.swing.JLabel Lbl_Bg_ClientView;
    private javax.swing.JLabel Lbl_Bg_PasswordChange;
    private javax.swing.JLabel Lbl_PasswordChange;
    public static javax.swing.JLabel Lbl_PopUp_Base;
    private javax.swing.JPasswordField Pfield_AdminPassword;
    public static javax.swing.JPasswordField Pfield_ConfirmNewPassword;
    public static javax.swing.JPasswordField Pfield_LastPassword;
    public static javax.swing.JPasswordField Pfield_NewPassword;
    public static javax.swing.JDialog PopUp_AdminLogin;
    private javax.swing.JScrollPane Scroll_Table_CarsList;
    private javax.swing.JTable Table_CarsList;
    private javax.swing.JTextField Tfield_AdminUser;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonEliminarClient;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonModificarClient;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAutos;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelFindo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFondoRegisCliente;
    private javax.swing.JLabel jLabelVentas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldAño;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCelular1;
    private javax.swing.JTextField jTextFieldColor;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldDireccion1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JTextField jTextFieldFechaNac;
    private javax.swing.JTextField jTextFieldFechaNac1;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldIdentificacion1;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldPlaca1;
    private javax.swing.JTextField jTextFieldPrecioCompra;
    private javax.swing.JTextField jTextFieldPrecioModelo;
    private javax.swing.JTextField jTextFieldPreciodeVenta;
    // End of variables declaration//GEN-END:variables

}
