/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio2.FrontEnd;

/**
 *
 * @author mariagutierrezgonzalez
 */
public class OpcionesAdministradorFrame extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesAdministradorFrame
     */
    public OpcionesAdministradorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IntFrame_ClientView = new javax.swing.JInternalFrame();
        IntFrame_BuyACar = new javax.swing.JInternalFrame();
        IntFrame_AdminLogin = new javax.swing.JInternalFrame();
        Button_ExitAdminLogin = new javax.swing.JButton();
        jButtonSeleccionarCLIENTES = new javax.swing.JButton();
        jButtonSeleccionarVENTAS = new javax.swing.JButton();
        jButtonSeleccionarAUTOS = new javax.swing.JButton();
        Lbl_Bg_AdminLogin = new javax.swing.JLabel();
        Scroll_Table_CarsList = new javax.swing.JScrollPane();
        Table_CarsList = new javax.swing.JTable();
        Lbl_Bg_ClientView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IntFrame_ClientView.setTitle("Vista de cliente");
        IntFrame_ClientView.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_ClientView.setMaximumSize(new java.awt.Dimension(960, 540));
        IntFrame_ClientView.setMinimumSize(new java.awt.Dimension(960, 540));
        IntFrame_ClientView.setPreferredSize(new java.awt.Dimension(960, 540));
        try {
            IntFrame_ClientView.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_ClientView.setVisible(true);
        IntFrame_ClientView.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IntFrame_BuyACar.setTitle("menu de compra");
        IntFrame_BuyACar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_BuyACar.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_BuyACar.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_BuyACar.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_BuyACar.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_BuyACar.setVisible(false);

        javax.swing.GroupLayout IntFrame_BuyACarLayout = new javax.swing.GroupLayout(IntFrame_BuyACar.getContentPane());
        IntFrame_BuyACar.getContentPane().setLayout(IntFrame_BuyACarLayout);
        IntFrame_BuyACarLayout.setHorizontalGroup(
            IntFrame_BuyACarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        IntFrame_BuyACarLayout.setVerticalGroup(
            IntFrame_BuyACarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        IntFrame_ClientView.getContentPane().add(IntFrame_BuyACar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_BuyACar.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_AdminLogin.setClosable(true);
        IntFrame_AdminLogin.setResizable(true);
        IntFrame_AdminLogin.setTitle("Opciones");
        IntFrame_AdminLogin.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_AdminLogin.setLayer(1);
        IntFrame_AdminLogin.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_AdminLogin.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_AdminLogin.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_AdminLogin.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_AdminLogin.setVisible(true);
        IntFrame_AdminLogin.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_AdminLoginInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_AdminLogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_ExitAdminLogin.setBackground(new java.awt.Color(149, 227, 244));
        Button_ExitAdminLogin.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        Button_ExitAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        Button_ExitAdminLogin.setText("Salir");
        Button_ExitAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExitAdminLoginActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Button_ExitAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 90, 30));

        jButtonSeleccionarCLIENTES.setBackground(new java.awt.Color(0, 51, 102));
        jButtonSeleccionarCLIENTES.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jButtonSeleccionarCLIENTES.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSeleccionarCLIENTES.setText("Seleccione aqui");
        jButtonSeleccionarCLIENTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarCLIENTESActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(jButtonSeleccionarCLIENTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 130, -1));

        jButtonSeleccionarVENTAS.setBackground(new java.awt.Color(0, 51, 102));
        jButtonSeleccionarVENTAS.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jButtonSeleccionarVENTAS.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSeleccionarVENTAS.setText("Seleccione aqui");
        jButtonSeleccionarVENTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarVENTASActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(jButtonSeleccionarVENTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 130, -1));

        jButtonSeleccionarAUTOS.setBackground(new java.awt.Color(0, 51, 102));
        jButtonSeleccionarAUTOS.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jButtonSeleccionarAUTOS.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSeleccionarAUTOS.setText("Seleccione aqui");
        jButtonSeleccionarAUTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarAUTOSActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(jButtonSeleccionarAUTOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 130, -1));

        Lbl_Bg_AdminLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/OpcionesAdmin.png"))); // NOI18N
        IntFrame_AdminLogin.getContentPane().add(Lbl_Bg_AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        IntFrame_ClientView.getContentPane().add(IntFrame_AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_AdminLogin.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        Scroll_Table_CarsList.setMaximumSize(new java.awt.Dimension(400, 400));
        Scroll_Table_CarsList.setMinimumSize(new java.awt.Dimension(400, 400));
        Scroll_Table_CarsList.setPreferredSize(new java.awt.Dimension(400, 400));

        Table_CarsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_CarsList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        Table_CarsList.setMaximumSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setMinimumSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setPreferredSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setShowGrid(false);
        Scroll_Table_CarsList.setViewportView(Table_CarsList);

        IntFrame_ClientView.getContentPane().add(Scroll_Table_CarsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 400, 400));

        Lbl_Bg_ClientView.setMaximumSize(new java.awt.Dimension(960, 510));
        Lbl_Bg_ClientView.setMinimumSize(new java.awt.Dimension(960, 510));
        Lbl_Bg_ClientView.setPreferredSize(new java.awt.Dimension(960, 510));
        IntFrame_ClientView.getContentPane().add(Lbl_Bg_ClientView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(IntFrame_ClientView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(IntFrame_ClientView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        try {
            IntFrame_ClientView.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ExitAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExitAdminLoginActionPerformed
        
    }//GEN-LAST:event_Button_ExitAdminLoginActionPerformed

    private void IntFrame_AdminLoginInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_AdminLoginInternalFrameClosed
        
    }//GEN-LAST:event_IntFrame_AdminLoginInternalFrameClosed

    private void jButtonSeleccionarCLIENTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarCLIENTESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeleccionarCLIENTESActionPerformed

    private void jButtonSeleccionarVENTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarVENTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeleccionarVENTASActionPerformed

    private void jButtonSeleccionarAUTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarAUTOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeleccionarAUTOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesAdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesAdministradorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_ExitAdminLogin;
    public static javax.swing.JInternalFrame IntFrame_AdminLogin;
    private javax.swing.JInternalFrame IntFrame_BuyACar;
    public static javax.swing.JInternalFrame IntFrame_ClientView;
    private javax.swing.JLabel Lbl_Bg_AdminLogin;
    private javax.swing.JLabel Lbl_Bg_ClientView;
    private javax.swing.JScrollPane Scroll_Table_CarsList;
    private javax.swing.JTable Table_CarsList;
    private javax.swing.JButton jButtonSeleccionarAUTOS;
    private javax.swing.JButton jButtonSeleccionarCLIENTES;
    private javax.swing.JButton jButtonSeleccionarVENTAS;
    // End of variables declaration//GEN-END:variables
}
