/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio2.FrontEnd;

/**
 *
 * @author mariagutierrezgonzalez
 */
public class RegistroAutoFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegistroAutoFrame
     */
    public RegistroAutoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IntFrame_ClientView = new javax.swing.JInternalFrame();
        IntFrame_AdminLogin = new javax.swing.JInternalFrame();
        Pfield_AdminPassword = new javax.swing.JPasswordField();
        Tfield_AdminUser = new javax.swing.JTextField();
        Btn_ConfirmAdminLogin = new javax.swing.JButton();
        Lbl_PasswordChange = new javax.swing.JLabel();
        Button_ExitAdminLogin = new javax.swing.JButton();
        Lbl_Bg_AdminLogin = new javax.swing.JLabel();
        IntFrame_BuyACar = new javax.swing.JInternalFrame();
        Scroll_Table_CarsList = new javax.swing.JScrollPane();
        Table_CarsList = new javax.swing.JTable();
        Lbl_Bg_ClientView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IntFrame_ClientView.setTitle("Vista de cliente");
        IntFrame_ClientView.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_ClientView.setMaximumSize(new java.awt.Dimension(960, 540));
        IntFrame_ClientView.setMinimumSize(new java.awt.Dimension(960, 540));
        IntFrame_ClientView.setPreferredSize(new java.awt.Dimension(960, 540));
        try {
            IntFrame_ClientView.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_ClientView.setVisible(true);
        IntFrame_ClientView.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IntFrame_AdminLogin.setClosable(true);
        IntFrame_AdminLogin.setResizable(true);
        IntFrame_AdminLogin.setTitle("Registrar Autos");
        IntFrame_AdminLogin.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_AdminLogin.setLayer(1);
        IntFrame_AdminLogin.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_AdminLogin.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_AdminLogin.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_AdminLogin.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_AdminLogin.setVisible(true);
        IntFrame_AdminLogin.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                IntFrame_AdminLoginInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        IntFrame_AdminLogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pfield_AdminPassword.setBackground(new java.awt.Color(199, 227, 255));
        Pfield_AdminPassword.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        IntFrame_AdminLogin.getContentPane().add(Pfield_AdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 185, 180, 25));

        Tfield_AdminUser.setBackground(new java.awt.Color(199, 227, 255));
        Tfield_AdminUser.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        IntFrame_AdminLogin.getContentPane().add(Tfield_AdminUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 141, 180, 25));

        Btn_ConfirmAdminLogin.setBackground(new java.awt.Color(44, 131, 218));
        Btn_ConfirmAdminLogin.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        Btn_ConfirmAdminLogin.setForeground(new java.awt.Color(199, 227, 255));
        Btn_ConfirmAdminLogin.setText("Ingresar");
        Btn_ConfirmAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConfirmAdminLoginActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Btn_ConfirmAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 110, -1));

        Lbl_PasswordChange.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        Lbl_PasswordChange.setForeground(new java.awt.Color(44, 131, 218));
        Lbl_PasswordChange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_PasswordChange.setText("CAMBIAR CONTRASEÑA");
        Lbl_PasswordChange.setToolTipText("");
        Lbl_PasswordChange.setAlignmentY(0.0F);
        Lbl_PasswordChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_PasswordChangeMouseClicked(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Lbl_PasswordChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 190, 30));

        Button_ExitAdminLogin.setBackground(new java.awt.Color(149, 227, 244));
        Button_ExitAdminLogin.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        Button_ExitAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        Button_ExitAdminLogin.setText("Salir");
        Button_ExitAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExitAdminLoginActionPerformed(evt);
            }
        });
        IntFrame_AdminLogin.getContentPane().add(Button_ExitAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 100, 30));

        Lbl_Bg_AdminLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorio2/FrontEnd/media/Fondo-Login.png"))); // NOI18N
        IntFrame_AdminLogin.getContentPane().add(Lbl_Bg_AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        IntFrame_ClientView.getContentPane().add(IntFrame_AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_AdminLogin.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        IntFrame_BuyACar.setTitle("menu de compra");
        IntFrame_BuyACar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        IntFrame_BuyACar.setMaximumSize(new java.awt.Dimension(700, 400));
        IntFrame_BuyACar.setMinimumSize(new java.awt.Dimension(700, 400));
        IntFrame_BuyACar.setPreferredSize(new java.awt.Dimension(700, 400));
        try {
            IntFrame_BuyACar.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        IntFrame_BuyACar.setVisible(false);

        javax.swing.GroupLayout IntFrame_BuyACarLayout = new javax.swing.GroupLayout(IntFrame_BuyACar.getContentPane());
        IntFrame_BuyACar.getContentPane().setLayout(IntFrame_BuyACarLayout);
        IntFrame_BuyACarLayout.setHorizontalGroup(
            IntFrame_BuyACarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        IntFrame_BuyACarLayout.setVerticalGroup(
            IntFrame_BuyACarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        IntFrame_ClientView.getContentPane().add(IntFrame_BuyACar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 700, 400));
        try {
            IntFrame_BuyACar.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        Scroll_Table_CarsList.setMaximumSize(new java.awt.Dimension(400, 400));
        Scroll_Table_CarsList.setMinimumSize(new java.awt.Dimension(400, 400));
        Scroll_Table_CarsList.setPreferredSize(new java.awt.Dimension(400, 400));

        Table_CarsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_CarsList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        Table_CarsList.setMaximumSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setMinimumSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setPreferredSize(new java.awt.Dimension(400, 400));
        Table_CarsList.setShowGrid(false);
        Scroll_Table_CarsList.setViewportView(Table_CarsList);

        IntFrame_ClientView.getContentPane().add(Scroll_Table_CarsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 400, 400));

        Lbl_Bg_ClientView.setMaximumSize(new java.awt.Dimension(960, 510));
        Lbl_Bg_ClientView.setMinimumSize(new java.awt.Dimension(960, 510));
        Lbl_Bg_ClientView.setPreferredSize(new java.awt.Dimension(960, 510));
        IntFrame_ClientView.getContentPane().add(Lbl_Bg_ClientView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(IntFrame_ClientView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(IntFrame_ClientView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        try {
            IntFrame_ClientView.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ConfirmAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConfirmAdminLoginActionPerformed
        Admin GenCredentials = new Admin();
        GenCredentials.setUser(Tfield_AdminUser.getText());
        GenCredentials.setPassword(String.valueOf(Pfield_AdminPassword.getPassword()));
        TheMagic.Autentication(GenCredentials);
    }//GEN-LAST:event_Btn_ConfirmAdminLoginActionPerformed

    private void Lbl_PasswordChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_PasswordChangeMouseClicked
        Pfield_AdminPassword.setText("");
        IntFrame_AdminLogin.setVisible(false);
        IntFrame_PasswordChange.setVisible(true);
    }//GEN-LAST:event_Lbl_PasswordChangeMouseClicked

    private void Button_ExitAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExitAdminLoginActionPerformed
        IntFrame_AdminLogin.setVisible(false);
        IntFrame_ClientView.setVisible(true);
    }//GEN-LAST:event_Button_ExitAdminLoginActionPerformed

    private void IntFrame_AdminLoginInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_IntFrame_AdminLoginInternalFrameClosed
        IntFrame_AdminView.setVisible(false);
        IntFrame_ClientView.setVisible(true);
    }//GEN-LAST:event_IntFrame_AdminLoginInternalFrameClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAutoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ConfirmAdminLogin;
    private javax.swing.JButton Button_ExitAdminLogin;
    public static javax.swing.JInternalFrame IntFrame_AdminLogin;
    private javax.swing.JInternalFrame IntFrame_BuyACar;
    public static javax.swing.JInternalFrame IntFrame_ClientView;
    private javax.swing.JLabel Lbl_Bg_AdminLogin;
    private javax.swing.JLabel Lbl_Bg_ClientView;
    private javax.swing.JLabel Lbl_PasswordChange;
    public static javax.swing.JPasswordField Pfield_AdminPassword;
    private javax.swing.JScrollPane Scroll_Table_CarsList;
    private javax.swing.JTable Table_CarsList;
    private javax.swing.JTextField Tfield_AdminUser;
    // End of variables declaration//GEN-END:variables
}
